### ISSUE TITLE
Receiving a warning in webpack 5

### ISSUE THREAD

**Issue by joseq-concentra** [kelyvin/generate-json-from-js-webpack-plugin#5]
Hello, thanks for creating this plugin!

I'm using it with webpack 5 and it outputs this warning:

(node:80030) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by ChadBailey** [comment]
Will this be fixed, or has this extension fallen into no maintenance? I really like what it does for my code base but don't want to make it a dependency only to have to inevitably remove it later once it finally causes a breaking issue.

**Comment by ChadBailey** [comment]
Fixed in my PR, please accept or give feedback...

**Comment by ChadBailey** [comment]
Also, thanks to [this code example](https://github.com/Badrpas/eacy/blob/cb2c1c7e9510ea614bed0d5a475d636c19855da0/lib/plugin.js) I found as well as the [official docs](https://webpack.js.org/contribute/writing-a-plugin/) for writing webpack plugins. I did this with no prior knowledge of writing webpack plugins and very beginner knowledge of webpack yet these got me to the solution.

Be warned that it may still be sub-optimal

**Comment by kelyvin** [comment]
Thanks for contributing the fix!
